services:
  mysql:
    image: mysql:8.0
    container_name: swyp-mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swyp
      MYSQL_USER: swyp
      MYSQL_PASSWORD: swyp1234
    volumes:
      - swyp-mysql-data:/var/lib/mysql

volumes:
  swyp-mysql-data: