spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:swyp}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: ${DB_USERNAME:swyp}
    password: ${DB_PASSWORD:swyp1234}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:swyp1234}

jwt:
  issuer: swyp
  secret-key: ${JWT_SECRET}
  access-token-ttl-ms: 604800000  # 개발용
#  access-token-ttl-ms: 900000
  refresh-token-ttl-ms: 604800000

springdoc:
  swagger-ui:
    operations-sorter: alpha
    persistAuthorization: true  # 새로고침 후에도 인증 헤더 유지

firebase:
  credentials:
    location: ${FIREBASE_CREDENTIAL_LOCATION}

oauth:
  kakao:
    app-id: ${KAKAO_APP_ID}
    admin-key: ${KAKAO_ADMIN_KEY}
  naver:
    client-id: ${NAVER_CLIENT_ID}
    client-secret: ${NAVER_CLIENT_SECRET}